name: coffee_shop_app
description: "Fake Project Coffee Shop Application"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#------------- PACKAGES --------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific

  #-------------- ./ End Package -------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #-------------- Local Assets ---------------#
  assets:
    - assets/logos/
    - assets/images/on_boarding_images/

  #-------------- Local Fonts --------------#
  fonts:
    - family: JakartaSans
      fonts:
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 800